name = "subonlybot"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
SUBMISSION_TOPICS = "#submissions"

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "TOPIC_DATA"
id = "93d1fd250c9a4c7f85d52d5998eb3232"
preview_id = "93d1fd250c9a4c7f85d52d5998eb3232"
